arxiv_db: /Users/leo/Data/arxiv/arxiv-metadata.db
arxiv_sources_dir: /Users/leo/Homepage/_scripts/arxiv/sources
homepage_arxiv_scripts: /Users/leo/Homepage/_scripts/arxiv
initial_arxiv_start_date: 2021-08-01
site_endpoint: /arxiv/

people_dirs:
  faculty: _departmentpeople/faculty
  postdoc: _departmentpeople/postdocs
  grad: _departmentpeople/gradstudents
  lecturer: _departmentpeople/lecturers
  emeriti: _departmentpeople/emeriti
  unpublished: _departmentpeople/_unpublished
